# 应用名称
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: w1
        predicates:
        - Path=/w/**
        uri: lb://spring-cloud-alibaba-nacos
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
server:
  port: 8090




