server:
  port: 8090
# 应用名称
spring:
  application:
    name: sample-gateway
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.0.237:8848
    gateway:
      discovery:
        locator:
          # 这个配置才能动态拉去服务
          enabled: true

