server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: oauth2-auth

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 7
    port: 6379
    host: 192.168.0.237
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.237:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
